In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import Ridge, Lasso, RidgeCV, LassoCV, ElasticNet, ElasticNetCV, LinearRegression
from sklearn.model_selection import train_test_split
import statsmodels.api as sm
import matplotlib.pyplot as plt
import seaborn as sns
from pandas_profiling import ProfileReport
import pickle

In [2]:
df=pd.read_csv('Admission_Prediction1.csv')
df

Serial No.  GRE Score  TOEFL Score  University Rating  SOP  LOR   CGPA  \
0             1        337          118                  4  4.5   4.5  9.65   
1             2        324          107                  4  4.0   4.5  8.87   
2             3        316          104                  3  3.0   3.5  8.00   
3             4        322          110                  3  3.5   2.5  8.67   
4             5        314          103                  2  2.0   3.0  8.21   
..          ...        ...          ...                ...  ...   ...   ...   
495         496        332          108                  5  4.5   4.0  9.02   
496         497        337          117                  5  5.0   5.0  9.87   
497         498        330          120                  5  4.5   5.0  9.56   
498         499        312          103                  4  4.0   5.0  8.43   
499         500        327          113                  4  4.5   4.5  9.04   

     Research  Chance of Admit  
0           1             0.92  
1           1             0.76  
2           1             0.72  
3           1             0.80  
4           0             0.65  
..        ...              ...  
495         1             0.87  
496         1             0.96  
497         1             0.93  
498         0             0.73  
499         0             0.84  

[500 rows x 9 columns]

In [ ]:
#We will find a model in which we will try to find whether we will be able to get admission or not

#In classification, we find the numbers but those numbers are fixed. but in regression the numbers are not fixed

In [3]:
pf=ProfileReport(df)

In [4]:
pf.to_widgets()

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render widgets:   0%|          | 0/1 [00:00<?, ?it/s]

In [ ]:
#There is some sort of linear relation available. So we will apply linear regression There is multicollinearity b/w features

#how to deal with mising values. going forward we will use imputors for missing values
#df['GRE Score']=df['GRE Score'].fillna(df['GRE Score'].mean()) #it will fill missing values with average of that column
#df['TOEFL Score']=df['TOEFL Score'].fillna(df['TOEFL Score'].mean())
#df['University Rating']=df['University Rating'].fillna(df['University Rating'].mean())
#instead of mean, we can even use median or mode or backward fill or forward fill or even algorithms.
#now check do we have missing values by df.describe() or df.isnull().sum()

In [5]:
#seial no. is of no use, so we will drop
df.drop(columns=['Serial No.'])

GRE Score  TOEFL Score  University Rating  SOP  LOR   CGPA  Research  \
0          337          118                  4  4.5   4.5  9.65         1   
1          324          107                  4  4.0   4.5  8.87         1   
2          316          104                  3  3.0   3.5  8.00         1   
3          322          110                  3  3.5   2.5  8.67         1   
4          314          103                  2  2.0   3.0  8.21         0   
..         ...          ...                ...  ...   ...   ...       ...   
495        332          108                  5  4.5   4.0  9.02         1   
496        337          117                  5  5.0   5.0  9.87         1   
497        330          120                  5  4.5   5.0  9.56         1   
498        312          103                  4  4.0   5.0  8.43         0   
499        327          113                  4  4.5   4.5  9.04         0   

     Chance of Admit  
0               0.92  
1               0.76  
2               0.72  
3               0.80  
4               0.65  
..               ...  
495             0.87  
496             0.96  
497             0.93  
498             0.73  
499             0.84  

[500 rows x 8 columns]

In [6]:
df

Serial No.  GRE Score  TOEFL Score  University Rating  SOP  LOR   CGPA  \
0             1        337          118                  4  4.5   4.5  9.65   
1             2        324          107                  4  4.0   4.5  8.87   
2             3        316          104                  3  3.0   3.5  8.00   
3             4        322          110                  3  3.5   2.5  8.67   
4             5        314          103                  2  2.0   3.0  8.21   
..          ...        ...          ...                ...  ...   ...   ...   
495         496        332          108                  5  4.5   4.0  9.02   
496         497        337          117                  5  5.0   5.0  9.87   
497         498        330          120                  5  4.5   5.0  9.56   
498         499        312          103                  4  4.0   5.0  8.43   
499         500        327          113                  4  4.5   4.5  9.04   

     Research  Chance of Admit  
0           1             0.92  
1           1             0.76  
2           1             0.72  
3           1             0.80  
4           0             0.65  
..        ...              ...  
495         1             0.87  
496         1             0.96  
497         1             0.93  
498         0             0.73  
499         0             0.84  

[500 rows x 9 columns]

In [7]:
#So we see that again we can see serial no., so we will use inplace operator
df.drop(columns=['Serial No.'], inplace=True)

In [8]:
df
#now serial no. is gone

GRE Score  TOEFL Score  University Rating  SOP  LOR   CGPA  Research  \
0          337          118                  4  4.5   4.5  9.65         1   
1          324          107                  4  4.0   4.5  8.87         1   
2          316          104                  3  3.0   3.5  8.00         1   
3          322          110                  3  3.5   2.5  8.67         1   
4          314          103                  2  2.0   3.0  8.21         0   
..         ...          ...                ...  ...   ...   ...       ...   
495        332          108                  5  4.5   4.0  9.02         1   
496        337          117                  5  5.0   5.0  9.87         1   
497        330          120                  5  4.5   5.0  9.56         1   
498        312          103                  4  4.0   5.0  8.43         0   
499        327          113                  4  4.5   4.5  9.04         0   

     Chance of Admit  
0               0.92  
1               0.76  
2               0.72  
3               0.80  
4               0.65  
..               ...  
495             0.87  
496             0.96  
497             0.93  
498             0.73  
499             0.84  

[500 rows x 8 columns]

In [9]:
#we will create our x and y
y=df['Chance of Admit']
y

0      0.92
1      0.76
2      0.72
3      0.80
4      0.65
       ... 
495    0.87
496    0.96
497    0.93
498    0.73
499    0.84
Name: Chance of Admit, Length: 500, dtype: float64

In [10]:
x=df.drop(columns=['Chance of Admit'])
x

GRE Score  TOEFL Score  University Rating  SOP  LOR   CGPA  Research
0          337          118                  4  4.5   4.5  9.65         1
1          324          107                  4  4.0   4.5  8.87         1
2          316          104                  3  3.0   3.5  8.00         1
3          322          110                  3  3.5   2.5  8.67         1
4          314          103                  2  2.0   3.0  8.21         0
..         ...          ...                ...  ...   ...   ...       ...
495        332          108                  5  4.5   4.0  9.02         1
496        337          117                  5  5.0   5.0  9.87         1
497        330          120                  5  4.5   5.0  9.56         1
498        312          103                  4  4.0   5.0  8.43         0
499        327          113                  4  4.5   4.5  9.04         0

[500 rows x 7 columns]

In [ ]:
#normalization or some sort of standardized operation is important.
#if we go back to pandas profiling, then we notice that ranges of datset column are varying a lot, so we can call StandardScaler and bring down into lower label.
#we can even use this data even without bringing down dataset into lower level. But if we donot bring it to lower scale, it will be tough for the model to understang the concrete relations.
#So if we can bring the dataset into lower scale without changing its meaning, then the model will be able to build relations in a better way 

In [11]:
#Standardize features by removing the mean and scaling to unit variance.(Press shift+tab to know more about StandardScaler)
#Standard score is somewhat similar to Z-statistics
#standard scaler means mean=0 and std dev=1. We are shifting our entire dataset where mean=0 and Standard dev=1 
scaler=StandardScaler()

In [12]:
#we wil try to fit our feature. Fit tansformation is a function associated with ScandardScaler
arr=scaler.fit_transform(x)
arr

array([[ 1.81923762,  1.77886545,  0.77558214, ...,  1.09894429,
         1.77680627,  0.88640526],
       [ 0.66714832, -0.03160087,  0.77558214, ...,  1.09894429,
         0.48585943,  0.88640526],
       [-0.0418297 , -0.52536441, -0.09979274, ...,  0.01730621,
        -0.95404281,  0.88640526],
       ...,
       [ 1.19888185,  2.10804114,  1.65095702, ...,  1.63976333,
         1.62785086,  0.88640526],
       [-0.39631872, -0.68995225,  0.77558214, ...,  1.63976333,
        -0.24236699, -1.12815215],
       [ 0.93301508,  0.95592621,  0.77558214, ...,  1.09894429,
         0.76721964, -1.12815215]])

In [13]:
#now we will store it into a dataframe
df1=pd.DataFrame(arr)

In [14]:
df1.profile_report()

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

In [15]:
#now if we compare the variable graphs with the previous one, we are able to see 0 mean in all the places. So this dataset is standardized. We are just shifting our dataset to a different scale. Previously mean was not equal to 0 and std dev was not equal to 1
df1

0         1         2         3         4         5         6
0    1.819238  1.778865  0.775582  1.137360  1.098944  1.776806  0.886405
1    0.667148 -0.031601  0.775582  0.632315  1.098944  0.485859  0.886405
2   -0.041830 -0.525364 -0.099793 -0.377773  0.017306 -0.954043  0.886405
3    0.489904  0.462163 -0.099793  0.127271 -1.064332  0.154847  0.886405
4   -0.219074 -0.689952 -0.975168 -1.387862 -0.523513 -0.606480 -1.128152
..        ...       ...       ...       ...       ...       ...       ...
495  1.376126  0.132987  1.650957  1.137360  0.558125  0.734118  0.886405
496  1.819238  1.614278  1.650957  1.642404  1.639763  2.140919  0.886405
497  1.198882  2.108041  1.650957  1.137360  1.639763  1.627851  0.886405
498 -0.396319 -0.689952  0.775582  0.632315  1.639763 -0.242367 -1.128152
499  0.933015  0.955926  0.775582  1.137360  1.098944  0.767220 -1.128152

[500 rows x 7 columns]

In [16]:
#now our dataset is  ranging in b/w some lower scale. Var of dataset is ot very high
df1.describe()
#mean is close to 0 values(e to the power -15). Std dev is approx 1(e to the power 00 means 1)
#Min max differences are not much. Its close and ranging b/w some of the defined ranges. (Its not like some of values are 1 and some are going to 500)

0             1             2             3             4  \
count  5.000000e+02  5.000000e+02  5.000000e+02  5.000000e+02  5.000000e+02   
mean   1.762146e-15  1.136868e-15  1.421085e-16 -8.526513e-17  4.263256e-17   
std    1.001002e+00  1.001002e+00  1.001002e+00  1.001002e+00  1.001002e+00   
min   -2.346008e+00 -2.500419e+00 -1.850542e+00 -2.397950e+00 -2.686789e+00   
25%   -7.508077e-01 -6.899523e-01 -9.751676e-01 -8.828175e-01 -5.235128e-01   
50%    4.679255e-02 -3.160087e-02 -9.979274e-02  1.272712e-01  1.730621e-02   
75%    7.557706e-01  7.913384e-01  7.755821e-01  6.323155e-01  5.581253e-01   
max    2.085104e+00  2.108041e+00  1.650957e+00  1.642404e+00  1.639763e+00   

                  5             6  
count  5.000000e+02  5.000000e+02  
mean   3.119283e-15 -7.815970e-17  
std    1.001002e+00  1.001002e+00  
min   -2.940115e+00 -1.128152e+00  
25%   -7.430227e-01 -1.128152e+00  
50%   -2.720919e-02  8.864053e-01  
75%    7.672196e-01  8.864053e-01  
max    2.223672e+00  8.864053e-01

In [17]:
#we will check again multicollinearity with the new dataset. Last time so much of correlation was there.
#we can do pearson plot or VIF. We will use VIF here
from statsmodels.stats.outliers_influence import variance_inflation_factor

In [18]:
arr.shape
#500 records in 1 single column

(500, 7)

In [19]:
#we need to extract the rows,so shape[0]
#for column, shape[1]
#For 7 columns, we need to find VIF
[variance_inflation_factor(arr,i)for i in range(arr.shape[1])]

[4.464249139118506,
 3.904213330817261,
 2.6210362171283177,
 2.8352103508865123,
 2.0335548605441,
 4.777991929494217,
 1.4940078664337448]

In [20]:
#we can store this information in some other dataframe.
#lets create vif datarame
vif_df=pd.DataFrame()

In [21]:
vif_df['vif']=[variance_inflation_factor(arr,i)for i in range(arr.shape[1])]
vif_df['feature']=x.columns

In [22]:
vif_df

vif            feature
0  4.464249          GRE Score
1  3.904213        TOEFL Score
2  2.621036  University Rating
3  2.835210                SOP
4  2.033555               LOR 
5  4.777992               CGPA
6  1.494008           Research

In [23]:
#vif score for each and coumn is lesser than 10. So we not supposed to drop any coumn or call any dimensionality reduction technique.
#We can use this arr dataset as it is. We are able to make sure that there is no multicollineaity
arr

array([[ 1.81923762,  1.77886545,  0.77558214, ...,  1.09894429,
         1.77680627,  0.88640526],
       [ 0.66714832, -0.03160087,  0.77558214, ...,  1.09894429,
         0.48585943,  0.88640526],
       [-0.0418297 , -0.52536441, -0.09979274, ...,  0.01730621,
        -0.95404281,  0.88640526],
       ...,
       [ 1.19888185,  2.10804114,  1.65095702, ...,  1.63976333,
         1.62785086,  0.88640526],
       [-0.39631872, -0.68995225,  0.77558214, ...,  1.63976333,
        -0.24236699, -1.12815215],
       [ 0.93301508,  0.95592621,  0.77558214, ...,  1.09894429,
         0.76721964, -1.12815215]])

In [24]:
#we will split dataset into 2 area. One for training and other for testing so that we will be able to perform testing operation on unknown dataset.
#test_size is a hyper-parameter. There is no hard and fast rule for this
train_test_split(arr,y,test_size=0.25)

[array([[ 0.31265931,  0.79133837,  0.77558214, ...,  1.09894429,
          0.46930883,  0.88640526],
        [-0.57356322, -0.19618871,  0.77558214, ..., -1.06433187,
         -0.3582212 , -1.12815215],
        [-0.39631872,  0.13298698, -0.09979274, ..., -0.52351283,
         -0.07686099, -1.12815215],
        ...,
        [ 2.08510438,  2.10804114,  0.77558214, ...,  0.55812525,
          2.22367248,  0.88640526],
        [ 0.04679255,  0.46216267, -0.09979274, ...,  1.09894429,
          0.88307384,  0.88640526],
        [ 1.55337086,  1.6142776 ,  1.65095702, ...,  1.09894429,
          0.81687144,  0.88640526]]),
 array([[-0.83942999, -0.36077656,  0.77558214, -0.37777315, -0.52351283,
         -1.05334642, -1.12815215],
        [ 0.75577058,  0.79133837,  0.77558214,  0.12727117,  0.01730621,
          0.56861243, -1.12815215],
        [ 0.48990382,  0.46216267,  1.65095702,  1.64240413,  0.55812525,
          0.86652324,  0.88640526],
        [ 1.19888185,  0.95592621,  1.65095

In [25]:
#this has given 4 tuples. So lets try to store this dataset into 4 variables
x_train, x_test, y_train, y_test = train_test_split(arr,y,test_size=0.25)

In [26]:
x_train
#we can see that our dataset is changing because by default it is going to split dataset in a random fashion
#In numpy for fixing random selection, we use a func named seed.
#in train_test, similar func named random_state is used

array([[-0.13045196, -1.01912795, -0.09979274, ...,  1.09894429,
         0.91617504, -1.12815215],
       [-1.01667449, -1.84206718,  0.77558214, ...,  1.09894429,
        -0.5237272 , -1.12815215],
       [-1.45978576, -0.8545401 , -0.09979274, ..., -1.06433187,
        -0.67268261, -1.12815215],
       ...,
       [-1.90289703, -1.34830364, -1.85054249, ..., -2.14596996,
        -1.66571863, -1.12815215],
       [-1.45978576, -0.8545401 , -0.97516761, ..., -1.60515091,
        -1.16920062, -1.12815215],
       [-1.63703027, -1.01912795, -0.97516761, ..., -1.60515091,
        -1.18575122, -1.12815215]])

In [27]:
x_train, x_test, y_train, y_test = train_test_split(arr,y,test_size=0.25, random_state=345)

In [28]:
x_train
#now we can see that it does not change, we have fixed therandomness

array([[-0.39631872, -0.68995225,  0.77558214, ...,  1.63976333,
        -0.24236699, -1.12815215],
       [-1.63703027, -1.01912795,  0.77558214, ...,  1.09894429,
        -1.46711143,  0.88640526],
       [-0.39631872,  0.13298698, -0.09979274, ..., -0.52351283,
        -0.07686099, -1.12815215],
       ...,
       [ 0.48990382,  1.28510191,  1.65095702, ...,  1.09894429,
         1.29683885,  0.88640526],
       [-1.63703027, -1.67747933, -0.97516761, ..., -0.52351283,
        -2.26154025, -1.12815215],
       [ 1.73061537,  1.94345329,  1.65095702, ...,  0.01730621,
         2.02506527,  0.88640526]])

In [29]:
lr=LinearRegression()

In [30]:
#fitting our feature and label
lr.fit(x_train, y_train)

LinearRegression()

In [31]:
#so we will store our lr model
pickle.dump(lr,open('admission_lr_model.pickle','wb'))

In [33]:
df

GRE Score  TOEFL Score  University Rating  SOP  LOR   CGPA  Research  \
0          337          118                  4  4.5   4.5  9.65         1   
1          324          107                  4  4.0   4.5  8.87         1   
2          316          104                  3  3.0   3.5  8.00         1   
3          322          110                  3  3.5   2.5  8.67         1   
4          314          103                  2  2.0   3.0  8.21         0   
..         ...          ...                ...  ...   ...   ...       ...   
495        332          108                  5  4.5   4.0  9.02         1   
496        337          117                  5  5.0   5.0  9.87         1   
497        330          120                  5  4.5   5.0  9.56         1   
498        312          103                  4  4.0   5.0  8.43         0   
499        327          113                  4  4.5   4.5  9.04         0   

     Chance of Admit  
0               0.92  
1               0.76  
2               0.72  
3               0.80  
4               0.65  
..               ...  
495             0.87  
496             0.96  
497             0.93  
498             0.73  
499             0.84  

[500 rows x 8 columns]

In [34]:
lr.predict([[337, 118, 4, 4.5, 4.5, 9.65, 1]])

array([9.83968564])

In [35]:
test1= scaler.transform([[337, 118, 4, 4.5, 4.5, 9.65, 1]])
lr.predict(test1)

c:\users\deepti kiran\appdata\local\programs\python\python39\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


array([0.95267498])

In [36]:
#now approx close result. lets check with another datset
test1= scaler.transform([[324, 107, 4, 4.0, 4.5, 8.87, 1]])
lr.predict(test1)
#our expectation was 0.76 and wegot 0.8.So its aprrox same. Its able to understand some sort of relations that we had in the dataset

c:\users\deepti kiran\appdata\local\programs\python\python39\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


array([0.80918107])

In [37]:
#prediction of physical file
model=pickle.load(open('admission_lr_model.pickle','rb'))
model.predict(test1)
#same result with object or stored file
#scaler model that we have created can also be stored

array([0.80918107])

In [38]:
#Score of my model,R square
#lr.score()
#expectation is 90% and our model is giving 80%, then improvement is needed and then productionize

#we can give the data that we have used in our training but thats not the correct approach because our model has already learnt the pattern from dataset.
#If I am looking for true score, we will have to give unknown dataset that our model has not seen
#25% of dataset was kept for testing, we will use that.
x_test

array([[-0.30769646,  0.29757483, -0.09979274,  0.63231549,  0.01730621,
         0.70101723, -1.12815215],
       [-0.30769646, -0.8545401 , -0.09979274, -1.3878618 , -0.52351283,
        -0.5071766 , -1.12815215],
       [ 0.66714832,  0.46216267, -0.09979274,  0.12727117, -0.52351283,
         1.06513044,  0.88640526],
       [ 1.99648213,  1.44968975,  0.77558214,  0.63231549,  0.01730621,
         2.02506527,  0.88640526],
       [ 0.1354148 , -0.19618871, -0.09979274, -1.3878618 , -0.52351283,
         0.12174622, -1.12815215],
       [-0.39631872, -0.36077656, -0.97516761, -1.3878618 , -1.06433187,
        -0.20926579, -1.12815215],
       [ 0.1354148 ,  0.29757483, -0.09979274,  0.12727117,  0.55812525,
         1.06513044,  0.88640526],
       [ 0.57852607, -0.03160087, -0.09979274,  0.12727117,  0.01730621,
        -0.04375979,  0.88640526],
       [ 1.46474861,  1.77886545,  1.65095702,  1.64240413,  1.63976333,
         1.28028825,  0.88640526],
       [ 0.75577058,  0.6267

In [39]:
y_test

289    0.79
167    0.64
371    0.89
148    0.96
391    0.71
       ... 
106    0.87
9      0.45
323    0.62
417    0.52
238    0.70
Name: Chance of Admit, Length: 125, dtype: float64

In [40]:
#Testing accuracy
lr.score(x_test, y_test)

0.7509361305609726

In [41]:
#let's create a function to create adjusted R-squared
def adj_r2(x,y):
    r2=lr.score(x,y)
    n=x.shape[0] #no. of rows
    p=x.shape[1] #no. of cols
    adjusted_r2=1-(1-r2)*(n-1)/(n-p-1)
    return adjusted_r2

In [42]:
adj_r2(x_test,y_test)
#adjusted R-square is little bit lesser than R-square
#this is our actual accuracy(may be)

0.7360348734150479

In [43]:
#If we have to increase the accuracy little bit, then we will try change the random state from 345 to 100.
x_train, x_test, y_train, y_test= train_test_split(arr, y, test_size=0.25, random_state=100)
lr.score(x_test, y_test)
#The score has changed

0.8347356206271066

In [44]:
adj_r2(x_test,y_test)
#when we changed random state from 345 to 100, our adjusted R-square has also increased

0.8248480081859934

In [45]:
#Which is the true score?Adjusted R-square or R-square?
#If we add more data for training purpose, the score will increase
x_train, x_test, y_train, y_test= train_test_split(arr, y, test_size=0.15, random_state=100)
lr.score(x_test, y_test)
#These numbers are experimental one. No one is going to tell that this is the expected value

#If random.seed is not used, then everytime we will give different data
#By inprovising, we can increase it to a certain extent, but not 100%

0.8488853039312444

In [46]:
#How to know the Actual equation that the model has bulit
lr.coef_

array([0.01955314, 0.01428037, 0.01058208, 0.00392493, 0.01668152,
       0.07214128, 0.0128272 ])

In [47]:
lr.intercept_

0.7211457455854196

In [ ]:
#Now we can build the dataset using the values of m and c

#Based on Lasso and Ridge, we will check that we have built the best model or not

In [48]:
#Implementation of Lasso:

#Lasso cross validation
#Cross validation is a technique to find the best possible parameter by doing random exp
#cv will be used heavily as hyper parameter
#here alphaas is same as lambda
#If cv=5, then it will divide our dataset(whether train or test or whole dataset) into 5 sets
lassocv=LassoCV(alphas=None, cv=5, max_iter=2000000, normalize=True)
lassocv.fit(x_train, y_train)
#initially alphas=None

c:\users\deepti kiran\appdata\local\programs\python\python39\lib\site-packages\sklearn\linear_model\_base.py:141: FutureWarning: 'normalize' was deprecated in version 1.0 and will be removed in 1.2.
If you wish to scale the data, use Pipeline with a StandardScaler in a preprocessing stage. To reproduce the previous behavior:

from sklearn.pipeline import make_pipeline

model = make_pipeline(StandardScaler(with_mean=False), Lasso())

If you wish to pass a sample_weight parameter, you need to pass it as a fit parameter to each step of the pipeline as follows:

kwargs = {s[0] + '__sample_weight': sample_weight for s in model.steps}
model.fit(X, y, **kwargs)

Set parameter alpha to: original_alpha * np.sqrt(n_samples). 
  warnings.warn(


LassoCV(cv=5, max_iter=2000000, normalize=True)

In [49]:
#optimal value of lambda. Lambda is unknown variable
lassocv.alpha_

4.203962663551952e-05

In [50]:
lasso=Lasso(alpha=lassocv.alpha_)
lasso.fit(x_train, y_train)

Lasso(alpha=4.203962663551952e-05)

In [51]:
lasso.score(x_test, y_test)

0.8444966837226585

In [52]:
#This is a linear regression model with Lasso

#If CV=5, then it wil divide our data into 5 sets and 4 sets will be used for training and 1 for testing;for 2nd iteration again it wil choose another 4 for traing and 1 for testing; and everytime it wil keep rotating the values of 4 and 1 dataset. If CV=50, then it wil divide our data into 50 sets and 49 sets will be used for training and 1 for testing.

In [53]:
#EVEN IN RIDGE, WE ARE SUPPOSED TO FIND OUT BEST POSSIBLE ALPHA VALUES

ridgecv=RidgeCV(alphas=(0.1, 1.0, 10.0), cv=10, normalize=True)
ridgecv.fit(x_train, y_train)
#argument used in alphas is for the length of size

c:\users\deepti kiran\appdata\local\programs\python\python39\lib\site-packages\sklearn\linear_model\_base.py:141: FutureWarning: 'normalize' was deprecated in version 1.0 and will be removed in 1.2.
If you wish to scale the data, use Pipeline with a StandardScaler in a preprocessing stage. To reproduce the previous behavior:

from sklearn.pipeline import make_pipeline

model = make_pipeline(StandardScaler(with_mean=False), Ridge())

If you wish to pass a sample_weight parameter, you need to pass it as a fit parameter to each step of the pipeline as follows:

kwargs = {s[0] + '__sample_weight': sample_weight for s in model.steps}
model.fit(X, y, **kwargs)

Set parameter alpha to: original_alpha * n_samples. 
  warnings.warn(
c:\users\deepti kiran\appdata\local\programs\python\python39\lib\site-packages\sklearn\linear_model\_base.py:141: FutureWarning: 'normalize' was deprecated in version 1.0 and will be removed in 1.2.
If you wish to scale the data, use Pipeline with a StandardScaler i

RidgeCV(cv=10, normalize=True)

In [54]:
#out of 3 alphas, selwct 1 possible one
ridgecv.alpha_

0.1

In [55]:
#we will try to keep higher range of alpha bcoz its a hyperparameter
np.random.uniform(0,10,50)
#50 records b/w 0 to 10
#we will give this data now in alphas parameter

array([4.33456381, 9.59452369, 0.18165189, 8.20243164, 8.16935539,
       1.96457497, 6.34801311, 5.8029862 , 8.08764384, 3.76858907,
       0.80193205, 9.36450091, 2.73573528, 4.62665386, 6.93182332,
       1.24166021, 2.60894746, 2.84095886, 1.62781224, 5.66055472,
       9.43516674, 5.44618934, 6.23420631, 1.35399137, 9.24928601,
       4.79357749, 1.62607679, 8.28428707, 3.72567812, 6.90179732,
       6.79679956, 0.4071833 , 1.1229124 , 5.93199245, 4.73325354,
       3.47136476, 9.86858735, 4.38874507, 1.22939463, 2.31836113,
       9.47261025, 4.06730887, 2.98514667, 1.2559873 , 4.18885664,
       1.67455861, 2.33251995, 4.06199672, 4.7517297 , 3.60625675])

In [56]:
ridgecv=RidgeCV(alphas=np.random.uniform(0,10,50), cv=10, normalize=True)
ridgecv.fit(x_train, y_train)

c:\users\deepti kiran\appdata\local\programs\python\python39\lib\site-packages\sklearn\linear_model\_base.py:141: FutureWarning: 'normalize' was deprecated in version 1.0 and will be removed in 1.2.
If you wish to scale the data, use Pipeline with a StandardScaler in a preprocessing stage. To reproduce the previous behavior:

from sklearn.pipeline import make_pipeline

model = make_pipeline(StandardScaler(with_mean=False), Ridge())

If you wish to pass a sample_weight parameter, you need to pass it as a fit parameter to each step of the pipeline as follows:

kwargs = {s[0] + '__sample_weight': sample_weight for s in model.steps}
model.fit(X, y, **kwargs)

Set parameter alpha to: original_alpha * n_samples. 
  warnings.warn(
c:\users\deepti kiran\appdata\local\programs\python\python39\lib\site-packages\sklearn\linear_model\_base.py:141: FutureWarning: 'normalize' was deprecated in version 1.0 and will be removed in 1.2.
If you wish to scale the data, use Pipeline with a StandardScaler i

c:\users\deepti kiran\appdata\local\programs\python\python39\lib\site-packages\sklearn\linear_model\_base.py:141: FutureWarning: 'normalize' was deprecated in version 1.0 and will be removed in 1.2.
If you wish to scale the data, use Pipeline with a StandardScaler in a preprocessing stage. To reproduce the previous behavior:

from sklearn.pipeline import make_pipeline

model = make_pipeline(StandardScaler(with_mean=False), Ridge())

If you wish to pass a sample_weight parameter, you need to pass it as a fit parameter to each step of the pipeline as follows:

kwargs = {s[0] + '__sample_weight': sample_weight for s in model.steps}
model.fit(X, y, **kwargs)

Set parameter alpha to: original_alpha * n_samples. 
  warnings.warn(
c:\users\deepti kiran\appdata\local\programs\python\python39\lib\site-packages\sklearn\linear_model\_base.py:141: FutureWarning: 'normalize' was deprecated in version 1.0 and will be removed in 1.2.
If you wish to scale the data, use Pipeline with a StandardScaler i

c:\users\deepti kiran\appdata\local\programs\python\python39\lib\site-packages\sklearn\linear_model\_base.py:141: FutureWarning: 'normalize' was deprecated in version 1.0 and will be removed in 1.2.
If you wish to scale the data, use Pipeline with a StandardScaler in a preprocessing stage. To reproduce the previous behavior:

from sklearn.pipeline import make_pipeline

model = make_pipeline(StandardScaler(with_mean=False), Ridge())

If you wish to pass a sample_weight parameter, you need to pass it as a fit parameter to each step of the pipeline as follows:

kwargs = {s[0] + '__sample_weight': sample_weight for s in model.steps}
model.fit(X, y, **kwargs)

Set parameter alpha to: original_alpha * n_samples. 
  warnings.warn(
c:\users\deepti kiran\appdata\local\programs\python\python39\lib\site-packages\sklearn\linear_model\_base.py:141: FutureWarning: 'normalize' was deprecated in version 1.0 and will be removed in 1.2.
If you wish to scale the data, use Pipeline with a StandardScaler i

c:\users\deepti kiran\appdata\local\programs\python\python39\lib\site-packages\sklearn\linear_model\_base.py:141: FutureWarning: 'normalize' was deprecated in version 1.0 and will be removed in 1.2.
If you wish to scale the data, use Pipeline with a StandardScaler in a preprocessing stage. To reproduce the previous behavior:

from sklearn.pipeline import make_pipeline

model = make_pipeline(StandardScaler(with_mean=False), Ridge())

If you wish to pass a sample_weight parameter, you need to pass it as a fit parameter to each step of the pipeline as follows:

kwargs = {s[0] + '__sample_weight': sample_weight for s in model.steps}
model.fit(X, y, **kwargs)

Set parameter alpha to: original_alpha * n_samples. 
  warnings.warn(
c:\users\deepti kiran\appdata\local\programs\python\python39\lib\site-packages\sklearn\linear_model\_base.py:141: FutureWarning: 'normalize' was deprecated in version 1.0 and will be removed in 1.2.
If you wish to scale the data, use Pipeline with a StandardScaler i

RidgeCV(alphas=array([4.04068044, 9.23213023, 3.10420035, 5.69946326, 1.1866227 ,
       6.49076702, 2.62523657, 2.46112046, 5.7513251 , 8.86976195,
       5.90179905, 2.46271512, 0.62737298, 4.87839672, 9.5514672 ,
       9.19298017, 9.6689502 , 0.05031998, 1.20740767, 4.91604418,
       5.4531337 , 2.91923617, 4.83947244, 3.73892497, 3.57971583,
       5.214555  , 6.31131754, 3.18928521, 9.21401108, 7.71360851,
       4.52485516, 2.19298313, 7.47129993, 1.23497237, 0.29423632,
       2.28389074, 3.06011849, 7.07308966, 5.90151981, 7.68731881,
       6.16280032, 9.22248298, 4.88921546, 9.54656241, 5.65672889,
       0.37958522, 6.29889629, 3.17232005, 3.49459778, 0.8033025 ]),
        cv=10, normalize=True)

In [57]:
ridgecv.alpha_
#now out of 50 datasets that we have given, it is able to finalizealpha value as this one

0.050319982077905445

In [58]:
#we will create ridge object with alpha
ridge_lr=Ridge(alpha=ridgecv.alpha_)
ridge_lr.fit(x_train, y_train)

Ridge(alpha=0.050319982077905445)

In [59]:
#score of model with testing
ridge_lr.score(x_test, y_test)

0.8443817580318868

In [ ]:
#Last time our accuracy in lasso was 84.44. With simple linear regression without ridhe or Lasso was 80.91
#with ridge and lasso, we are able to get best possible model

In [60]:
#Lets try to test this with ElasticNet

elastic=ElasticNetCV(alphas=None, cv=10)
elastic.fit(x_train, y_train)

ElasticNetCV(cv=10)

In [61]:
elastic.alpha_

0.001838953845953152

In [62]:
#So, alpha is the above

#For elastic, 2 things are req, lambda and alpha
#L1 ratio is actual alpha and alpha is lambda here

#Here, whatever is said as alpha is basically a lambda.

In [63]:
elastic.l1_ratio_

0.5

In [64]:
elastic_lr=ElasticNet(alpha=elastic.alpha_, l1_ratio=elastic.l1_ratio_)

In [65]:
elastic_lr.fit(x_train, y_train)

ElasticNet(alpha=0.001838953845953152)

In [66]:
elastic_lr.score(x_test, y_test)

0.8444647115313421

All the 3: lasso, ridge and elastic are giving aprrox same accuracy So we have built a stable model becoz we are able to get same accuracy with all the 3. We have not built an overfitted model. This is just for verifiation.

In ideal cases, Adjusted r-square is less than R-square

Not only used to verify the model accuracy. we can productionize it as well. We can convert or create a pickle file and then productionize
If we give large value of max_iteration, training size also increase but it does not steps up to give higher accuracy. Lets suppose error=0, again and again 0 or diff b/w y and y hat=0, in that case there is no meaning of giving 1 lakh or more. If huge amt of data is there, then it makes sense, but otherwise we are just wasting our computation resources

In real life, 1+1=2. But in AI, it can be anything bcoz it just understands the relations. If we are using multiplication operation, things will be different and if we are using subtraction operation, things will be different. So if data variance is different, added data may give less accuracy. But if we give relevant data with same distribution and same variance, then there is chance that it will increase or adjust the parameter in a better way.

In all the cases, we are doing the same thing. But the difference is where we are calculating error func, we are trying to decrease the degree of freedom of changes which happens in m.